import type { Cents, FilingStatus, TaxBracket, TaxRulePack, TaxSource } from "./types";
import { projectedTaxRules } from "./tax";

export type TaxLotTerm="short"|"long";
export interface TaxLot { id:string; acquiredOn:string|null; marketValueCents:Cents; federalBasisCents:Cents; californiaBasisCents:Cents }
export interface LossCarryforwards { federalShortCents:Cents; federalLongCents:Cents; californiaShortCents:Cents; californiaLongCents:Cents }
export interface RetirementTaxIncome {
  pensionsCents:Cents; retirementDistributionsCents:Cents; shortTermGainsCents:Cents; rentalIncomeCents:Cents; interestCents:Cents; nonqualifiedDividendsCents:Cents;
  qualifiedDividendsCents:Cents; longTermGainsCents:Cents; unrecaptured1250GainsCents:Cents; socialSecurityBenefitsCents:Cents; taxExemptInterestCents:Cents;
  nontaxableIncomeCents:Cents; netInvestmentIncomeCents:Cents;
}
export interface RetirementTaxDeductions { mortgageInterestCents:Cents; stateAndLocalTaxesCents:Cents; charitableCents:Cents; medicalCents:Cents; qcdCents:Cents }
export interface RetirementTaxInput { year:number; filingStatus:FilingStatus; income:Partial<RetirementTaxIncome>; deductions?:Partial<RetirementTaxDeductions>; losses?:Partial<LossCarryforwards>; penaltiesCents?:Cents; thresholdInflationBps?:number; taxUnitAges?:readonly number[]; mfsLivedApartAllYear?:boolean; passiveRentalLossCents?:Cents }
export interface TaxBracketSlice { kind:"ordinary"|"preferential"|"unrecaptured-1250"; taxableCents:Cents; rateBps:number; taxCents:Cents }
export interface RetirementTaxResult {
  year:number; rulePackYear:number; projectedFrozen:boolean; sources:readonly TaxSource[]; federalAgiCents:Cents; californiaAgiCents:Cents; federalDeductionCents:Cents; californiaDeductionCents:Cents;
  federalTaxableIncomeCents:Cents; californiaTaxableIncomeCents:Cents; taxableSocialSecurityCents:Cents; provisionalIncomeCents:Cents; federalIncomeTaxCents:Cents; californiaIncomeTaxCents:Cents;
  niitCents:Cents; federalAdditionalTaxCents:Cents; californiaCreditsCents:Cents; californiaAdditionalTaxCents:Cents; penaltiesCents:Cents; totalLiabilityCents:Cents; effectiveRateBps:number;
  federalShortGainCents:Cents; federalLongGainCents:Cents; californiaNetGainCents:Cents; carryforwards:LossCarryforwards; bracketSlices:readonly TaxBracketSlice[]; estimateQuality:"estimate"; limitations:readonly string[]; unsupported:readonly string[];
}

const zeroIncome:RetirementTaxIncome={pensionsCents:0,retirementDistributionsCents:0,shortTermGainsCents:0,rentalIncomeCents:0,interestCents:0,nonqualifiedDividendsCents:0,qualifiedDividendsCents:0,longTermGainsCents:0,unrecaptured1250GainsCents:0,socialSecurityBenefitsCents:0,taxExemptInterestCents:0,nontaxableIncomeCents:0,netInvestmentIncomeCents:0};
const zeroDeductions:RetirementTaxDeductions={mortgageInterestCents:0,stateAndLocalTaxesCents:0,charitableCents:0,medicalCents:0,qcdCents:0};
const zeroLosses:LossCarryforwards={federalShortCents:0,federalLongCents:0,californiaShortCents:0,californiaLongCents:0};
const taxSlices=(amount:number,brackets:readonly TaxBracket[],kind:TaxBracketSlice["kind"],floor=0)=>{const out:TaxBracketSlice[]=[];let previous=0;for(const bracket of brackets){const cap=bracket.upToCents??Infinity,slice=Math.max(0,Math.min(floor+amount,cap)-Math.max(previous,floor));if(slice)out.push({kind,taxableCents:slice,rateBps:bracket.rateBps,taxCents:Math.round(slice*bracket.rateBps/10_000)});previous=cap;if(floor+amount<=cap)break}return out};
const sumTax=(s:readonly TaxBracketSlice[])=>s.reduce((n,x)=>n+x.taxCents,0);
const lossLimit=(status:FilingStatus)=>status==="married-separate"?1500_00:3000_00;
function netLosses(shortGain:number,longGain:number,shortCarry:number,longCarry:number,status:FilingStatus){let short=shortGain-shortCarry,long=longGain-longCarry;if(short<0&&long>0){const n=Math.min(-short,long);short+=n;long-=n}else if(long<0&&short>0){const n=Math.min(-long,short);long+=n;short-=n}const ordinaryOffset=Math.min(lossLimit(status),Math.max(0,-short-long));let remaining=ordinaryOffset;if(short<0){const used=Math.min(-short,remaining);short+=used;remaining-=used}if(long<0)long+=Math.min(-long,remaining);return {shortGain:Math.max(0,short),longGain:Math.max(0,long),ordinaryOffset,shortCarry:Math.max(0,-short),longCarry:Math.max(0,-long)}}
function taxableSocialSecurity(benefits:number,provisional:number,status:FilingStatus,livedApart=false){if(status==="married-separate"&&!livedApart)return Math.round(benefits*.85);const joint=status==="married-joint",base=joint?32_000_00:25_000_00,upper=joint?44_000_00:34_000_00;if(provisional<=base)return 0;const first=Math.min(benefits*.5,(upper-base)*.5,Math.max(0,provisional-base)*.5);return Math.round(Math.min(benefits*.85,first+Math.max(0,provisional-upper)*.85))}
const saltCap=(year:number,agi:number,status:FilingStatus)=>{if(year>=2030)return status==="married-separate"?5_000_00:10_000_00;const f=Math.pow(1.01,Math.max(0,year-2025)),cap=Math.round((status==="married-separate"?20_000_00:40_000_00)*f/10_000)*10_000,start=Math.round((status==="married-separate"?250_000_00:500_000_00)*f/10_000)*10_000;return Math.max(status==="married-separate"?5_000_00:10_000_00,cap-Math.round(Math.max(0,agi-start)*.30))};

export function calculateRetirementTax(input:RetirementTaxInput):RetirementTaxResult{
  const income={...zeroIncome,...input.income},deductions={...zeroDeductions,...input.deductions},losses={...zeroLosses,...input.losses};
  for(const [name,value] of Object.entries({...income,...deductions,...losses,penaltiesCents:input.penaltiesCents??0}))if(!Number.isSafeInteger(value)||(value<0&&!name.includes("Gains")))throw new RangeError(`${name} must be safe integer cents`);
  const pack=projectedTaxRules(input.year,input.thresholdInflationBps??0),status=input.filingStatus,ages=input.taxUnitAges??[],eligibleQcd=ages.some(age=>age>=70.5),qcd=Math.min(income.retirementDistributionsCents,deductions.qcdCents,eligibleQcd?Math.round(111_000_00*Math.pow(1+(input.thresholdInflationBps??0)/10_000,Math.max(0,input.year-2026))):0),ordinaryBeforeLoss=income.pensionsCents+income.retirementDistributionsCents-qcd+income.shortTermGainsCents+income.rentalIncomeCents+income.interestCents+income.nonqualifiedDividendsCents;
  const fedNet=netLosses(income.shortTermGainsCents,income.longTermGainsCents,losses.federalShortCents,losses.federalLongCents,status),caNet=netLosses(income.shortTermGainsCents,income.longTermGainsCents,losses.californiaShortCents,losses.californiaLongCents,status);
  const ordinaryWithoutSs=ordinaryBeforeLoss-income.shortTermGainsCents+fedNet.shortGain-fedNet.ordinaryOffset,provisional=ordinaryWithoutSs+income.qualifiedDividendsCents+fedNet.longGain+income.taxExemptInterestCents+Math.round(income.socialSecurityBenefitsCents/2),taxableSs=taxableSocialSecurity(income.socialSecurityBenefitsCents,provisional,status,input.mfsLivedApartAllYear);
  const federalAgi=Math.max(0,ordinaryWithoutSs+taxableSs+income.qualifiedDividendsCents+fedNet.longGain),medicalFloor=Math.round(federalAgi*.075),itemized=deductions.mortgageInterestCents+Math.min(deductions.stateAndLocalTaxesCents,saltCap(input.year,federalAgi,status))+deductions.charitableCents+Math.max(0,deductions.medicalCents-medicalFloor),seniorCount=ages.filter(x=>x>=65).length,ordinarySenior=seniorCount*(status==="married-joint"||status==="married-separate"?1650_00:2050_00),enhancedAllowed=input.year>=2025&&input.year<=2028&&status!=="married-separate",enhancedBase=enhancedAllowed?seniorCount*6000_00:0,enhancedStart=status==="married-joint"?150_000_00:75_000_00,enhanced=Math.max(0,enhancedBase-Math.round(Math.max(0,federalAgi-enhancedStart)*.06)),federalDeduction=Math.max(pack.federal[status].standardDeductionCents+ordinarySenior,itemized)+enhanced;
  const preferential=income.qualifiedDividendsCents+fedNet.longGain,ordinaryTaxable=Math.max(0,federalAgi-federalDeduction-preferential),preferentialTaxable=Math.min(preferential,Math.max(0,federalAgi-federalDeduction-ordinaryTaxable));
  const ordinarySlices=taxSlices(ordinaryTaxable,pack.federal[status].brackets,"ordinary"),preferentialSlices=taxSlices(preferentialTaxable,pack.federalLongTermCapitalGains[status],"preferential",ordinaryTaxable),section1250=Math.min(income.unrecaptured1250GainsCents,preferentialTaxable),section1250Extra=Math.max(0,Math.round(section1250*pack.unrecapturedSection1250MaxRateBps/10_000)-sumTax(taxSlices(section1250,pack.federalLongTermCapitalGains[status],"preferential",ordinaryTaxable)));
  const federalIncomeTax=sumTax(ordinarySlices)+sumTax(preferentialSlices)+section1250Extra,californiaAgi=Math.max(0,ordinaryBeforeLoss-income.shortTermGainsCents+caNet.shortGain+caNet.longGain-caNet.ordinaryOffset),caItemized=deductions.mortgageInterestCents+deductions.stateAndLocalTaxesCents+deductions.charitableCents+Math.max(0,deductions.medicalCents-Math.round(californiaAgi*.075)),caDeduction=Math.max(pack.california[status].standardDeductionCents,caItemized),caTaxable=Math.max(0,californiaAgi-caDeduction),caBaseTax=sumTax(taxSlices(caTaxable,pack.california[status].brackets,"ordinary")),caCredit=Math.min(caBaseTax,(status==="married-joint"?306_00:153_00)+seniorCount*153_00),caAdditional=Math.round(Math.max(0,caTaxable-1_000_000_00)*100/10_000),caTax=caBaseTax-caCredit+caAdditional;
  const investmentIncome=income.netInvestmentIncomeCents||income.interestCents+income.nonqualifiedDividendsCents+income.qualifiedDividendsCents+fedNet.shortGain+fedNet.longGain+Math.max(0,income.rentalIncomeCents),niit=Math.round(Math.min(investmentIncome,Math.max(0,federalAgi-pack.netInvestmentIncomeThresholdCents[status]))*380/10_000),penalties=input.penaltiesCents??0,total=federalIncomeTax+caTax+niit+penalties,limitations=["AMT","self-employment tax","foreign tax","unprovided credits","multi-state residency",...(input.passiveRentalLossCents?[`$${(input.passiveRentalLossCents/100).toLocaleString()} passive rental loss preserved as suspended; release rules are not modeled`]:[]),...(!eligibleQcd&&deductions.qcdCents?["QCD target excluded because no tax-unit member is age 70½"]:[])];
  return {year:input.year,rulePackYear:pack.year,projectedFrozen:input.year>pack.year,sources:pack.sources,federalAgiCents:federalAgi,californiaAgiCents:californiaAgi,federalDeductionCents:federalDeduction,californiaDeductionCents:caDeduction,federalTaxableIncomeCents:ordinaryTaxable+preferentialTaxable,californiaTaxableIncomeCents:caTaxable,taxableSocialSecurityCents:taxableSs,provisionalIncomeCents:provisional,federalIncomeTaxCents:federalIncomeTax,californiaIncomeTaxCents:caTax,niitCents:niit,federalAdditionalTaxCents:niit,californiaCreditsCents:caCredit,californiaAdditionalTaxCents:caAdditional,penaltiesCents:penalties,totalLiabilityCents:total,effectiveRateBps:federalAgi?Math.round(total*10_000/federalAgi):0,federalShortGainCents:fedNet.shortGain,federalLongGainCents:fedNet.longGain,californiaNetGainCents:caNet.shortGain+caNet.longGain,carryforwards:{federalShortCents:fedNet.shortCarry,federalLongCents:fedNet.longCarry,californiaShortCents:caNet.shortCarry,californiaLongCents:caNet.longCarry},bracketSlices:[...ordinarySlices,...preferentialSlices],estimateQuality:"estimate",limitations,unsupported:limitations};
}

export function lotTerm(acquiredOn:string,disposedOn:string):TaxLotTerm { const acquired=new Date(`${acquiredOn}T00:00:00Z`),disposed=new Date(`${disposedOn}T00:00:00Z`),anniversary=new Date(Date.UTC(acquired.getUTCFullYear()+1,acquired.getUTCMonth(),acquired.getUTCDate()));return disposed>anniversary?"long":"short" }
export function selectTaxLots(lots:readonly TaxLot[],proceedsCents:Cents,disposedOn:string){let remaining=proceedsCents;const ranked=[...lots].sort((a,b)=>{const gainA=a.marketValueCents-a.federalBasisCents,gainB=b.marketValueCents-b.federalBasisCents;if((gainA<0)!==(gainB<0))return gainA<0?-1:1;const longA=a.acquiredOn&&lotTerm(a.acquiredOn,disposedOn)==="long",longB=b.acquiredOn&&lotTerm(b.acquiredOn,disposedOn)==="long";if(longA!==longB)return longA?-1:1;return b.federalBasisCents/Math.max(1,b.marketValueCents)-a.federalBasisCents/Math.max(1,a.marketValueCents)});return ranked.flatMap(lot=>{if(!remaining||!lot.marketValueCents)return [];const sold=Math.min(remaining,lot.marketValueCents),ratio=sold/lot.marketValueCents;remaining-=sold;return [{lotId:lot.id,proceedsCents:sold,federalBasisCents:Math.round(lot.federalBasisCents*ratio),californiaBasisCents:Math.round(lot.californiaBasisCents*ratio),term:lot.acquiredOn?lotTerm(lot.acquiredOn,disposedOn):null,reviewRequired:lot.acquiredOn===null}]})}
