import type { Account, AnnualProjection, Asset, RecurringEntry } from "./types";
import type { RetirementCalculationInput, RetirementOutlook, RetirementOutlookYear, RetirementPropertyYear } from "./retirement";
import { occurrences, recurringAmount } from "./projection";
import { calculateRetirementTax, type LossCarryforwards } from "./retirementTax";

const cents=(n:number)=>Math.max(0,Math.round(n));
const monthReturn=(bps:number)=>Math.pow(1+bps/10_000,1/12)-1;
const iso=(year:number,month:number,day=1)=>`${year}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`;
export function ageOnDate(birthDate:string,onDate:string){
  const birth=new Date(`${birthDate}T00:00:00Z`),on=new Date(`${onDate}T00:00:00Z`);
  let months=(on.getUTCFullYear()-birth.getUTCFullYear())*12+on.getUTCMonth()-birth.getUTCMonth();if(on.getUTCDate()<birth.getUTCDate())months--;
  const anchor=new Date(Date.UTC(birth.getUTCFullYear(),birth.getUTCMonth()+months,birth.getUTCDate())),next=new Date(Date.UTC(anchor.getUTCFullYear(),anchor.getUTCMonth()+1,birth.getUTCDate()));
  return months/12+Math.max(0,on.getTime()-anchor.getTime())/Math.max(1,next.getTime()-anchor.getTime())/12;
}
export const rmdStartAge=(birthDate:string)=>Number(birthDate.slice(0,4))>=1960?75:73;
const UNIFORM=[27.4,26.5,25.5,24.6,23.7,22.9,22.0,21.1,20.2,19.4,18.5,17.7,16.8,16.0,15.2,14.4,13.7,12.9,12.2,11.5,10.8,10.1,9.5,8.9,8.4,7.8,7.3,6.8,6.4,6.0,5.6,5.2,4.9,4.6,4.3,4.1,3.9,3.7,3.5,3.4,3.3,3.1,3.0,2.9,2.8,2.7,2.5,2.3,2.0,1.9];
export const uniformLifetimeFactor=(age:number)=>age<72?undefined:UNIFORM[Math.min(UNIFORM.length-1,Math.max(0,Math.floor(age)-72))];
const taxClass=(a:Account)=>a.subtype==="traditional-ira"||a.subtype==="employer-pre-tax"?"pre-tax":a.subtype==="roth-ira"||a.subtype==="employer-roth"?"roth":"taxable";
const progressive=(income:number,brackets:readonly [number,number][])=>{let tax=0,last=0;for(const [cap,rate] of brackets){const slice=Math.max(0,Math.min(income,cap)-last);tax+=slice*rate;last=cap;if(income<=cap)break}return cents(tax)};
const householdTax=(ordinary:number,gains:number,ss:number)=>{
  const provisional=Math.max(0,ordinary+gains+ss/2),taxableSs=Math.min(ss*.85,Math.max(0,(provisional-3_200_000)*.85));
  const federal=progressive(Math.max(0,ordinary+taxableSs-3_200_000),[[2_480_000,.10],[10_080_000,.12],[21_120_000,.22],[40_260_000,.24],[51_200_000,.32],[76_800_000,.35],[Infinity,.37]]);
  const capital=progressive(gains,[[9_670_000,0],[60_000_000,.15],[Infinity,.20]]);
  const california=progressive(Math.max(0,ordinary+gains-1_100_000),[[2_200_000,.02],[5_200_000,.04],[8_200_000,.06],[11_400_000,.08],[Infinity,.093]]);
  return federal+capital+california;
};
const annualExpense=(entry:RecurringEntry,year:number,cutoffYear:number,scenario:RetirementCalculationInput["scenario"])=>{
  let total=0;const changes=scenario.events.filter(e=>(e.type==="recurring-change"||e.type==="income-change")&&e.entryId===entry.id&&e.date<=`${cutoffYear}-12-31`).sort((a,b)=>a.date.localeCompare(b.date)),base=changes.length?(changes.at(-1)! as {amountCents:number}).amountCents:entry.amountCents;
  for(let month=1;month<=12;month++){const key=iso(year,month).slice(0,7),count=occurrences({...entry,startDate:`${cutoffYear}-12-01`},key);if(!count)continue;total+=recurringAmount(entry,base,key,entry.annualGrowthBps??scenario.assumptions.inflationBps,(year-cutoffYear-1)*12+month,count)}return total;
};

export function calculateRetirementOutlook(input:RetirementCalculationInput&{people?:readonly {id:string;birthDate?:string|null;name?:string}[];recurring?:readonly RecurringEntry[];preset?:unknown}):RetirementOutlook{
  const retirementYears=Object.values(input.plan.retirementYears??{}),cutoffYear=retirementYears.length?Math.max(...retirementYears):input.plan.retirementYear,firstRetirementYear=cutoffYear+1;
  const cutoffProjection=input.projections.find(p=>p.year===cutoffYear),cutoffMonth=cutoffProjection?.months.find(m=>m.month===`${cutoffYear}-12`);
  const missingData:string[]=[];
  if(!cutoffMonth?.balances)missingData.push(`Extend the selected Plan through December 31, ${cutoffYear}.`);
  for(const person of input.people??[])if(!person.birthDate)missingData.push(`${person.name??"Household member"}: birth date is required.`);
  for(const account of input.accounts){if(!account.ownerPersonId)missingData.push(`${account.name}: owner is required.`);if(!account.subtype)missingData.push(`${account.name}: account subtype is required.`);if(account.subtype==="taxable-brokerage"&&account.taxableCostBasisCents==null)missingData.push(`${account.name}: taxable cost basis is required.`);if(taxClass(account)==="roth"&&(account.rothContributionBasisCents==null||account.rothOpeningYear==null))missingData.push(`${account.name}: Roth contribution basis and opening year are required.`)}
  const propertyRows=cutoffMonth?.properties?.filter(p=>p.status==="active"||p.status==="owner-occupied")??[],propertyIds=new Set(propertyRows.map(p=>p.assetId));
  for(const row of propertyRows.filter(p=>p.rentCents+p.aduIncomeCents>0)){const asset=input.assets.find(a=>a.id===row.assetId);if(asset?.rentalTaxBasisCents==null||asset.rentalBuildingBasisCents==null)missingData.push(`${row.name}: rental tax and building basis are required.`)}
  if(input.plan.expenseBuckets.some(b=>b.mode==="percent"))missingData.push("Percentage expenses require review and conversion to monthly or annual amounts.");
  if((input.plan.scheduledIncome??[]).some(x=>!x.classification||x.classification==="unclassified"))missingData.push("Classify every scheduled income source.");
  const manualAnnual=input.plan.expenseBuckets.reduce((s,b)=>s+(b.mode==="monthly"?b.monthlyCents*12:b.mode==="annual"?b.annualCents:0),0);
  const planEntries=(input.recurring??[]).filter(e=>e.kind==="expense"&&e.startDate<=`${cutoffYear}-12-31`&&(!e.endDate||e.endDate>=`${cutoffYear}-12-31`)&&e.taxTreatment!=="pretax"&&!/(mortgage|property tax|hoa|maintenance|transfer|contribution)/i.test(e.name));
  if((input.plan.spendingMode??"manual")==="manual"&&manualAnnual<=0)missingData.push("Add a positive retirement spending budget.");
  if(input.plan.spendingMode==="plan"&&!planEntries.length)missingData.push("No eligible recurring Plan expenses are active at the cutoff.");
  for(const asset of input.assets.filter(a=>(input.plan.liquidatableAssetIds??input.plan.selectedSourceIds).includes(a.id)))if(asset.taxableCostBasisCents==null)missingData.push(`${asset.name}: taxable cost basis is required before liquidation.`);
  const balances=new Map(input.accounts.map(a=>[a.id,cents(cutoffMonth?.balances?.accounts[a.id]??0)])),basis=new Map(input.accounts.map(a=>[a.id,cents(a.taxableCostBasisCents??a.rothContributionBasisCents??0)]));
  const assets=input.assets.filter(a=>!propertyIds.has(a.id)).map(a=>({...a,value:cents(cutoffMonth?.balances?.assets[a.id]??0),basis:cents(a.taxableCostBasisCents??0)}));
  const properties=propertyRows.map(row=>{const asset=input.assets.find(a=>a.id===row.assetId),liability=input.liabilities.find(l=>l.id===row.liabilityId);return {id:row.assetId,name:row.name,value:cents(row.assetValueCents??0),mortgage:cents(row.mortgageBalanceCents??0),rate:liability?.annualRateBps??0,payment:row.principalCents+row.interestCents,rent:row.rentCents+row.aduIncomeCents,operating:row.propertyTaxCents+row.insuranceCents+row.hoaCents+row.maintenanceCents,growth:asset?.annualGrowthBps??0,rentGrowth:input.scenario.assumptions.inflationBps}});
  const otherDebts=input.liabilities.filter(l=>!propertyRows.some(p=>p.liabilityId===l.id)).map(l=>({...l,balance:cents(cutoffMonth?.balances?.liabilities[l.id]??0)}));
  const order=[...(input.plan.withdrawalAccountOrder??[]),...input.accounts.map(a=>a.id)].filter((id,i,a)=>a.indexOf(id)===i),liquidIds=new Set(input.plan.liquidatableAssetIds??input.plan.selectedSourceIds),earlyRoth=new Set(input.plan.earlyRothAccountIds??[]);
  const portfolioParts=[...input.accounts.map(a=>({id:a.id,name:a.name,kind:"account" as const,valueCents:balances.get(a.id)??0})),...properties.map(p=>({id:p.id,name:p.name,kind:"property" as const,valueCents:p.value-p.mortgage})),...assets.map(a=>({id:a.id,name:a.name,kind:"asset" as const,valueCents:a.value})),...otherDebts.map(d=>({id:d.id,name:d.name,kind:"liability" as const,valueCents:-d.balance}))];
  const cutoffAccountBalanceCents=[...balances.values()].reduce((s,n)=>s+n,0),cutoffAssetValueCents=properties.reduce((s,p)=>s+p.value,0)+assets.reduce((s,a)=>s+a.value,0),cutoffLiabilityBalanceCents=properties.reduce((s,p)=>s+p.mortgage,0)+otherDebts.reduce((s,d)=>s+d.balance,0),cutoffBalanceCents=cutoffAccountBalanceCents+cutoffAssetValueCents-cutoffLiabilityBalanceCents;
  const rows:RetirementOutlookYear[]=[];let firstDepletionYear:number|undefined,losses:LossCarryforwards={federalShortCents:0,federalLongCents:0,californiaShortCents:0,californiaLongCents:0},priorYearTax=0,priorYearAgi=0;
  for(let offset=0;offset<50;offset++){
    const year=firstRetirementYear+offset,beginningSpendableCents=[...balances.values()].reduce((s,n)=>s+n,0)+assets.filter(a=>liquidIds.has(a.id)).reduce((s,a)=>s+a.value,0),accountStart=new Map(balances),returns=new Map<string,number>(),withdrawn=new Map<string,number>(),gains=new Map<string,number>(),rmds=new Map<string,number>();
    let grossRent=0,propertyCosts=0,debtService=0,taxableRental=0;const propertyAnnual:RetirementPropertyYear[]=[];
    for(const p of properties){const startValue=p.value,startMortgage=p.mortgage;let rent=0,cost=0,debt=0;for(let month=1;month<=12;month++){rent+=p.rent;cost+=p.operating;if(p.mortgage>0){const interest=cents(p.mortgage*p.rate/120_000),pay=Math.min(p.mortgage+interest,p.payment),principal=Math.max(0,pay-interest);p.mortgage-=principal;debt+=pay}p.value=cents(p.value*(1+monthReturn(p.growth)));p.rent=cents(p.rent*(1+monthReturn(p.rentGrowth)));p.operating=cents(p.operating*(1+monthReturn(input.scenario.assumptions.inflationBps)))}grossRent+=rent;propertyCosts+=cost;debtService+=debt;taxableRental+=Math.max(0,rent-cost-(startMortgage-p.mortgage===0?debt:debt-(startMortgage-p.mortgage))-cents((input.assets.find(a=>a.id===p.id)?.rentalBuildingBasisCents??0)/27.5));propertyAnnual.push({id:p.id,name:p.name,grossRentCents:rent,operatingExpenseCents:cost,debtServiceCents:debt,netCashFlowCents:rent-cost-debt,endingValueCents:p.value,endingMortgageCents:p.mortgage,endingEquityCents:p.value-p.mortgage});void startValue}
    let scheduled=0,ss=0,nontaxable=0;const incomeSources=[] as RetirementOutlookYear["incomeSources"];
    for(const source of input.plan.scheduledIncome??[])if(year>=source.startYear){const amount=cents(source.annualAmountCents*Math.pow(1+source.annualGrowthBps/10_000,year-source.startYear));scheduled+=amount;if(source.classification==="social-security")ss+=amount;if(source.classification==="nontaxable")nontaxable+=amount;incomeSources.push({id:source.id,name:source.name,kind:"scheduled",amountCents:amount})}
    let rmd=0;for(const account of input.accounts.filter(a=>taxClass(a)==="pre-tax")){const birth=input.people?.find(p=>p.id===account.ownerPersonId)?.birthDate;if(!birth||ageOnDate(birth,`${year}-12-31`)<rmdStartAge(birth))continue;const factor=uniformLifetimeFactor(ageOnDate(birth,`${year}-12-31`))!,amount=Math.min(balances.get(account.id)??0,cents((balances.get(account.id)??0)/factor));balances.set(account.id,(balances.get(account.id)??0)-amount);withdrawn.set(account.id,amount);rmds.set(account.id,amount);rmd+=amount;incomeSources.push({id:account.id,name:`${account.name} RMD`,kind:"rmd",amountCents:amount})}
    const inflation=Math.pow(1+input.scenario.assumptions.inflationBps/10_000,offset),lifestyle=(input.plan.spendingMode??"manual")==="plan"?planEntries.reduce((s,e)=>s+annualExpense(e,year,cutoffYear,input.scenario),0):cents(manualAnnual*inflation),requiredDebt=otherDebts.reduce((s,d)=>s+(d.balance>0?Math.min(d.balance+d.balance*d.annualRateBps/10_000,d.minimumPaymentCents*12):0),0),spending=lifestyle+propertyCosts+debtService+requiredDebt;
    let ordinary=scheduled-ss-nontaxable+taxableRental+rmd,tax=householdTax(ordinary,0,ss),cash=grossRent-propertyCosts-debtService+scheduled+rmd-tax,need=Math.max(0,spending-(propertyCosts+debtService)-cash),withdrawals=rmd,realized=0,penalties=0;
    for(const id of order){if(need<=0)break;const account=input.accounts.find(a=>a.id===id);if(!account)continue;let available=balances.get(id)??0;if(!available)continue;const kind=taxClass(account),birth=input.people?.find(p=>p.id===account.ownerPersonId)?.birthDate,age=birth?ageOnDate(birth,iso(year,1)):0,basisAvailable=basis.get(id)??0;if(kind==="roth"&&age<59.5){if(!earlyRoth.has(id))continue;available=Math.min(available,basisAvailable)}const rate=kind==="pre-tax"?.35:kind==="taxable"?.20*Math.max(0,1-basisAvailable/Math.max(1,available)):0;const take=Math.min(available,cents(need/Math.max(.01,1-rate)));balances.set(id,(balances.get(id)??0)-take);withdrawn.set(id,(withdrawn.get(id)??0)+take);withdrawals+=take;let gain=kind==="taxable"?cents(take*Math.max(0,1-basisAvailable/Math.max(1,available))):0;realized+=gain;gains.set(id,gain);if(kind==="taxable")basis.set(id,Math.max(0,basisAvailable-(take-gain)));if(kind==="roth")basis.set(id,Math.max(0,basisAvailable-take));const ageAtSeparation=birth?ageOnDate(birth,`${cutoffYear}-12-31`):0,employer55=account.subtype==="employer-pre-tax"&&ageAtSeparation>=55;if(kind==="pre-tax"&&age<59.5&&!employer55)penalties+=cents(take*.10);ordinary+=kind==="pre-tax"?take:0;cash+=take;need=Math.max(0,spending-(propertyCosts+debtService)-cash)}
    for(const asset of assets.filter(a=>liquidIds.has(a.id))){if(need<=0)break;const take=Math.min(asset.value,cents(need/.8)),ratio=asset.value?asset.basis/asset.value:0,gain=cents(take*(1-ratio));asset.value-=take;asset.basis=Math.max(0,asset.basis-(take-gain));withdrawals+=take;realized+=gain;cash+=take;need=Math.max(0,spending-(propertyCosts+debtService)-cash)}
    const taxStatement=calculateRetirementTax({year,filingStatus:input.filingStatus??"single",income:{pensionsCents:Math.max(0,ordinary-rmd-taxableRental),retirementDistributionsCents:rmd+input.accounts.filter(a=>taxClass(a)==="pre-tax").reduce((s,a)=>s+Math.max(0,(withdrawn.get(a.id)??0)-(rmds.get(a.id)??0)),0),rentalIncomeCents:Math.max(0,taxableRental),longTermGainsCents:realized,socialSecurityBenefitsCents:ss,netInvestmentIncomeCents:Math.max(0,taxableRental)+realized},losses,penaltiesCents:penalties,priorYearTaxCents:priorYearTax||undefined,priorYearAgiCents:priorYearAgi||undefined});
    losses=taxStatement.carryforwards;priorYearTax=taxStatement.totalLiabilityCents;priorYearAgi=taxStatement.federalAgiCents;tax=taxStatement.totalLiabilityCents;cash=grossRent-propertyCosts-debtService+scheduled+withdrawals-tax;need=Math.max(0,spending-(propertyCosts+debtService)-cash);const surplus=Math.max(0,cash-(spending-propertyCosts-debtService));if(surplus&&input.accounts[0])balances.set(input.accounts[0].id,(balances.get(input.accounts[0].id)??0)+surplus);
    for(const account of input.accounts){const before=balances.get(account.id)??0,after=cents(before*(1+account.annualReturnBps/10_000));balances.set(account.id,after);returns.set(account.id,after-before)}for(const asset of assets)asset.value=cents(asset.value*(1+asset.annualGrowthBps/10_000));for(const debt of otherDebts){for(let m=0;m<12&&debt.balance>0;m++){const interest=cents(debt.balance*debt.annualRateBps/120_000),pay=Math.min(debt.balance+interest,debt.minimumPaymentCents);debt.balance=Math.max(0,debt.balance-Math.max(0,pay-interest))}}
    const endingSpendableCents=[...balances.values()].reduce((s,n)=>s+n,0)+assets.filter(a=>liquidIds.has(a.id)).reduce((s,a)=>s+a.value,0),totalAssetsCents=[...balances.values()].reduce((s,n)=>s+n,0)+assets.reduce((s,a)=>s+a.value,0)+properties.reduce((s,p)=>s+p.value,0),totalDebtCents=properties.reduce((s,p)=>s+p.mortgage,0)+otherDebts.reduce((s,d)=>s+d.balance,0),netWorthCents=totalAssetsCents-totalDebtCents;
    if((need>0||endingSpendableCents<=0)&&firstDepletionYear===undefined)firstDepletionYear=year;
    const accounts=input.accounts.map(a=>({id:a.id,name:a.name,beginningCents:accountStart.get(a.id)??0,returnsCents:returns.get(a.id)??0,withdrawalsCents:withdrawn.get(a.id)??0,realizedGainsCents:gains.get(a.id)??0,rmdCents:rmds.get(a.id)??0,endingCents:balances.get(a.id)??0}));
    const accountRecon=accounts.reduce((s,a)=>s+a.beginningCents+a.returnsCents-a.withdrawalsCents-a.endingCents,0)+surplus;
    rows.push({year,beginningSpendableCents,endingSpendableCents,grossIncomeCents:grossRent+scheduled+rmd,employmentIncomeCents:0,rentalIncomeCents:grossRent,scheduledIncomeCents:scheduled,otherIncomeCents:0,taxAndPenaltyCents:tax,afterTaxIncomeCents:grossRent+scheduled+rmd-tax,spendingCents:spending,excessCents:cash-(spending-propertyCosts-debtService),withdrawalsCents:withdrawals,endingBalanceCents:endingSpendableCents,totalAssetsCents,totalDebtCents,netWorthCents,rmdCents:rmd,incomeSources,accounts,properties:propertyAnnual,reconciliationDifferenceCents:accountRecon,taxStatement});
  }
  const complete=missingData.length===0,warnings=[...new Set(missingData)];return {years:rows,cutoffYear,firstRetirementYear,cutoffBalanceCents,cutoffAccountBalanceCents,cutoffAssetValueCents,cutoffLiabilityBalanceCents,portfolioParts,firstDepletionYear,endingBalanceCents:rows.at(-1)?.endingSpendableCents??0,ready:complete?firstDepletionYear===undefined:null,complete,missingData:warnings,warnings,preset:"baseline"};
}
