import { describe, expect, it } from "vitest";
import { annualBucketAmount, calculateRetirement, defaultRetirementPlan, type RetirementCalculationInput, type RetirementPlanRecord } from "./retirement";
import type { Scenario } from "./types";
const scenario:Scenario={id:"s",name:"Plan",assumptions:{inflationBps:300,thresholdInflationBps:300},assumptionsInherited:false,events:[],contributions:[],withdrawals:[],horizon:{start:"2026-01",months:24}};
const plan=(patch:Partial<RetirementPlanRecord>={}):RetirementPlanRecord=>({...defaultRetirementPlan(2026),householdId:"h",selectedScenarioId:"s",...patch});
const input=(p:RetirementPlanRecord):RetirementCalculationInput=>({plan:p,currentYear:2026,scenario,projections:[],assets:[],liabilities:[],accounts:[{id:"taxable",name:"Brokerage",kind:"investment",balanceCents:10_000_000,annualReturnBps:700,liquid:true}]});
describe("retirement spending",()=>{
 it("supports monthly, annual, and after-tax percentage buckets",()=>{expect(annualBucketAmount({id:"m",name:"Housing",mode:"monthly",monthlyCents:100_000},6_000_000)).toBe(1_200_000);expect(annualBucketAmount({id:"a",name:"Travel",mode:"annual",annualCents:500_000},6_000_000)).toBe(500_000);expect(annualBucketAmount({id:"p",name:"Food",mode:"percent",percentBps:2500},6_000_000)).toBe(1_500_000)});
 it("allows percentages over 100% and reports the shortfall",()=>{const result=calculateRetirement(input(plan({portfolioItems:[{id:"x",kind:"stock",name:"Stocks",targetBalanceCents:10_000_000,sourceAccountId:"taxable",taxClass:"roth",annualReturnBps:0}],selectedSourceIds:["taxable"],expenseBuckets:[{id:"p",name:"Everything",mode:"percent",percentBps:12_000}]}))).selected;expect(result.plannedSpendingCents).toBeGreaterThan(result.spendableIncomeCents);expect(result.leftoverCents).toBeLessThan(0)});
});
describe("retirement funding",()=>{
 it("does not count one Plan source twice",()=>{const target={kind:"stock" as const,name:"Stocks",targetBalanceCents:10_000_000,sourceAccountId:"taxable",taxClass:"taxable" as const,annualReturnBps:700};const result=calculateRetirement(input(plan({selectedSourceIds:["taxable"],portfolioItems:[{...target,id:"one"},{...target,id:"two"}]}))).selected;expect(result.projectedCapitalCents).toBe(10_000_000);expect(result.requiredFundingCents).toBe(20_000_000);expect(result.fundingGapCents).toBe(10_000_000)});
 it("includes selected assets and subtracts selected liabilities",()=>{const base=input(plan({selectedSourceIds:["taxable","home","mortgage"]})),result=calculateRetirement({...base,assets:[{id:"home",name:"Home",valueCents:50_000_000,annualGrowthBps:0}],liabilities:[{id:"mortgage",name:"Mortgage",balanceCents:30_000_000,annualRateBps:0,minimumPaymentCents:0}]}).selected;expect(result.projectedCapitalCents).toBe(32_100_000)});
 it("uses vested private-equity value consistently in the first and projected years",()=>{const holding={priceCents:1000,priceDate:"2026-01-01",sellToCover:false,grants:[{id:"g",ownerPersonId:"p",grantDate:"2026-01-01",grantPriceCents:1000,unitsMicros:2_000_000,vestEvents:[{id:"v1",date:"2026-09-01",unitsMicros:1_000_000},{id:"v2",date:"2027-09-01",unitsMicros:1_000_000}]}]},base=input(plan({selectedSourceIds:["equity"]})),assets=[{id:"equity",name:"Equity",valueCents:2_000,annualGrowthBps:0,equityHolding:holding}];const before=calculateRetirement({...base,assets,asOfDate:"2026-08-18"}).selected,after=calculateRetirement({...base,assets,asOfDate:"2026-09-02"}).selected;expect(before.projectedCapitalCents).toBe(0);expect(after.projectedCapitalCents).toBe(1_070)});
 it("holds a desired property's purchase price fixed until the selected retirement year",()=>{const property={id:"p",kind:"property" as const,origin:"manual" as const,name:"Home",valueCents:10_000_000,monthlyRentCents:0,downPaymentBps:2000,purchaseCostBps:300,mortgageRateBps:600,mortgageTermYears:30,appreciationBps:1000,propertyTaxBps:100,annualInsuranceCents:0,monthlyHoaCents:0,maintenanceBps:100,incomeGrowthBps:300},base=input(plan({portfolioItems:[property]})),flat={...base,scenario:{...base.scenario,assumptions:{...base.scenario.assumptions,inflationBps:0}}},now=calculateRetirement({...flat,plan:{...flat.plan,retirementYear:2026}}).selected,later=calculateRetirement({...flat,plan:{...flat.plan,retirementYear:2027}}).selected;expect(now.requiredFundingCents).toBe(2_300_000);expect(later.requiredFundingCents).toBe(2_300_000)});
 it("includes a transferred ADU build cost in property funding",()=>{const base=input(plan({selectedSourceIds:["taxable"],portfolioItems:[{id:"adu",kind:"property",origin:"investment",name:"Home and ADU",valueCents:50_000_000,monthlyRentCents:0,downPaymentBps:2000,purchaseCostBps:300,mortgageRateBps:0,mortgageTermYears:30,appreciationBps:0,propertyTaxBps:0,annualInsuranceCents:0,monthlyHoaCents:0,maintenanceBps:0,incomeGrowthBps:0,homeSquareFeet:1000,aduSquareFeet:500,aduBuildYear:1,aduBuildCostCents:15_000_000,aduMonthlyRentCents:200_000}]})),result=calculateRetirement({...base,accounts:[{...base.accounts[0],balanceCents:100_000_000}]}).selected;expect(result.portfolioPurchased).toBe(true);expect(result.spendableIncomeCents).toBeGreaterThan(0)});
 it("taxes California property on assessed basis while maintenance follows market value",()=>{const base=input(plan({selectedSourceIds:["taxable"],portfolioItems:[{id:"rental",kind:"property",origin:"investment",name:"Rental",valueCents:100_000_000,monthlyRentCents:2_000_000,downPaymentBps:10000,purchaseCostBps:0,mortgageRateBps:0,mortgageTermYears:30,appreciationBps:1000,propertyTaxBps:100,annualInsuranceCents:0,monthlyHoaCents:0,maintenanceBps:0,incomeGrowthBps:0}]})),result=calculateRetirement({...base,accounts:[{...base.accounts[0],balanceCents:100_000_000}]}).selected;expect(result.spendableIncomeCents).toBe(23_000_000)});
 it("delays retirement until affordable and starts the ADU clock at purchase",()=>{const property={id:"adu",kind:"property" as const,origin:"investment" as const,name:"Rental",valueCents:25_000_000,monthlyRentCents:100_000,downPaymentBps:10000,purchaseCostBps:0,mortgageRateBps:0,mortgageTermYears:30,appreciationBps:0,propertyTaxBps:0,annualInsuranceCents:0,monthlyHoaCents:0,maintenanceBps:0,incomeGrowthBps:0,homeSquareFeet:1000,aduSquareFeet:500,aduBuildYear:3,aduBuildCostCents:0,aduMonthlyRentCents:100_000},base=input(plan({retirementYear:2026,selectedSourceIds:["taxable"],portfolioItems:[property]})),month=(balance:number)=>({balances:{accounts:{taxable:balance},assets:{},privateStock:{},liabilities:{}}}),result=calculateRetirement({...base,scenario:{...base.scenario,horizon:{...base.scenario.horizon,months:48}},projections:[{year:2026,months:[month(25_000_000)]},{year:2027,months:[month(25_000_000)]},{year:2028,months:[month(25_000_000)]}] as any});expect(result.selectedYearAffordable).toBe(false);expect(result.acquisitionYear).toBe(2027);expect(result.years.find(x=>x.year===2026)?.portfolioPurchased).toBe(false);expect(result.years.find(x=>x.year===2027)?.spendableIncomeCents).toBe(1_165_049);expect(result.years.find(x=>x.year===2029)?.spendableIncomeCents).toBe(2_196_340)});
});
