import {useEffect,useMemo,useRef,useState} from "react";
import {calculateInvestmentComparison,defaultInvestmentAssumptions,type InvestmentAssumptions,type InvestmentComparisonRecord} from "./domain/investment";
import type {Repository} from "./repository";

const cash=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(c/100);
const fields:{key:keyof InvestmentAssumptions;label:string;kind:"money"|"percent"|"number";advanced?:boolean;step?:string}[]=[
  {key:"homePriceCents",label:"Home price",kind:"money"},{key:"downPaymentBps",label:"Down payment",kind:"percent"},{key:"mortgageRateBps",label:"Mortgage rate",kind:"percent"},{key:"mortgageTermYears",label:"Mortgage term (years)",kind:"number"},
  {key:"monthlyRentCents",label:"Current monthly rent",kind:"money"},{key:"stockReturnBps",label:"Stock return",kind:"percent"},{key:"homeAppreciationBps",label:"Home appreciation",kind:"percent"},{key:"horizonYears",label:"Projection horizon (years)",kind:"number"},
  {key:"purchaseCostBps",label:"Purchase costs",kind:"percent",advanced:true},{key:"sellingCostBps",label:"Selling costs",kind:"percent",advanced:true},{key:"rentGrowthBps",label:"Rent growth",kind:"percent",advanced:true},{key:"propertyTaxBps",label:"Property tax",kind:"percent",advanced:true},
  {key:"annualInsuranceCents",label:"Annual insurance",kind:"money",advanced:true},{key:"insuranceGrowthBps",label:"Insurance growth",kind:"percent",advanced:true},{key:"monthlyHoaCents",label:"Monthly HOA",kind:"money",advanced:true},{key:"hoaGrowthBps",label:"HOA growth",kind:"percent",advanced:true},{key:"maintenanceBps",label:"Annual maintenance",kind:"percent",advanced:true},
];
const show=(value:number,kind:string)=>kind==="money"?(value/100).toString():kind==="percent"?(value/100).toString():value.toString();
const parse=(value:string,kind:string)=>Number(value)*(kind==="money"?100:kind==="percent"?100:1);

export function InvestmentView({initial,repository}:{initial?:InvestmentComparisonRecord|null;repository:Repository}){
  const base=initial?.assumptions??defaultInvestmentAssumptions;
  const [draft,setDraft]=useState<Record<string,string>>(()=>Object.fromEntries(fields.map(f=>[f.key,show(base[f.key],f.kind)])));
  const revision=useRef(initial?.revision??1),[saveState,setSaveState]=useState<"idle"|"saving"|"saved"|"error">("idle"),[scrub,setScrub]=useState<number|null>(null),[retryToken,setRetryToken]=useState(0);
  const assumptions=useMemo(()=>Object.fromEntries(fields.map(f=>[f.key,parse(draft[f.key],f.kind)])) as unknown as InvestmentAssumptions,[draft]);
  const calculation=useMemo(()=>calculateInvestmentComparison(assumptions),[assumptions]);
  useEffect(()=>{if(!calculation.ok||!repository.updateInvestmentComparison)return;setSaveState("saving");const timer=window.setTimeout(async()=>{try{const saved=await repository.updateInvestmentComparison!({assumptions,expectedRevision:revision.current});revision.current=saved.revision;setSaveState("saved")}catch{setSaveState("error")}},450);return()=>window.clearTimeout(timer)},[assumptions,calculation.ok,repository,retryToken]);
  const retry=()=>setRetryToken(n=>n+1);
  const update=(key:string,value:string)=>setDraft(old=>({...old,[key]:value}));
  return <div className="content investment-view">
    <section className="card investment-assumptions"><div className="card-title"><div><p className="eyebrow">Illustrative defaults</p><h2>Compare buying with renting and investing</h2></div><span className={`save-state ${saveState}`} role="status" aria-live="polite">{saveState==="saving"?"Saving…":saveState==="saved"?"Saved":saveState==="error"?<button onClick={retry}>Save failed — retry</button>:""}</span></div>
      <p className="muted">This projection is independent of your plan, accounts, assets, and transactions.</p>
      <div className="investment-fields">{fields.filter(f=>!f.advanced).map(f=><Field key={f.key} field={f} value={draft[f.key]} update={update}/>)}</div>
      <details><summary>Advanced assumptions</summary><div className="investment-fields">{fields.filter(f=>f.advanced).map(f=><Field key={f.key} field={f} value={draft[f.key]} update={update}/>)}</div></details>
    </section>
    {!calculation.ok?<section className="card investment-error" role="alert"><h2>Adjust the assumptions to compare</h2>{calculation.errors.map((e,i)=><p key={i}>{e.message}</p>)}</section>:<Results result={calculation.result} horizon={assumptions.horizonYears} scrub={scrub} setScrub={setScrub}/>} 
    <p className="muted projection-note">Projections use deterministic assumptions and nominal dollars, not market forecasts. Hypothetical sale proceeds subtract selling costs; keeping or renting out the home remains an option. Taxes, PMI, utilities, refinancing, and other investments are excluded.</p>
  </div>
}
function Field({field,value,update}:{field:typeof fields[number];value:string;update:(k:string,v:string)=>void}){return <label>{field.label}<span className="input-affix">{field.kind==="money"&&<i>$</i>}<input aria-label={field.label} inputMode="decimal" type="number" min="0" step={field.kind==="percent"?"0.1":"1"} value={value} onChange={e=>update(field.key,e.target.value)}/>{field.kind==="percent"&&<i>%</i>}</span></label>}
function Results({result,horizon,scrub,setScrub}:{result:Extract<ReturnType<typeof calculateInvestmentComparison>,{ok:true}>["result"];horizon:number;scrub:number|null;setScrub:(n:number|null)=>void}){
  const end=result.months.at(-1)!,point=result.months[scrub??result.months.length-1],equityDiff=end.stockValueCents-end.equityCents,saleDiff=end.stockValueCents-end.saleProceedsCents;
  const leader=equityDiff>=0?"Renting and investing":"Buying";
  const timing=(items:typeof result.equityCrossovers)=>items[0]?`Year ${items[0].year}, month ${(items[0].month-1)%12+1}`:"No crossover";
  return <><section className="investment-summary"><article className="card"><p className="eyebrow">At year {horizon}</p><h2>{leader} is ahead</h2><strong>{cash(Math.abs(equityDiff))}</strong><small>difference vs. paper equity</small></article><article className="card"><p>Versus net sale proceeds</p><strong>{saleDiff>=0?"+":"−"}{cash(Math.abs(saleDiff))}</strong><small>after assumed selling costs</small></article><article className="card"><p>First crossover</p><strong>{timing(result.equityCrossovers)}</strong><small>paper equity · {timing(result.saleCrossovers)} after sale</small></article></section>
    <section className="card investment-chart"><div className="card-title"><div><h2>Projected values</h2><p className="muted">Year {Math.ceil(point.month/12)||0}: Stock {cash(point.stockValueCents)} · Equity {cash(point.equityCents)} · Sale {cash(point.saleProceedsCents)}</p></div><div className="chart-legend"><span className="stock">Stock portfolio</span><span className="equity">Home equity</span><span className="sale">Sale proceeds</span></div></div><Chart result={result} scrub={scrub??result.months.length-1} setScrub={setScrub}/></section>
    <section className="card annual-results"><h2>Annual projection</h2><div className="table-scroll"><table><thead><tr><th>Year</th><th>Stock value</th><th>Home value</th><th>Mortgage</th><th>Equity</th><th>Sale proceeds</th><th>Owner outlay</th><th>Rent</th><th>Stock contributions</th></tr></thead><tbody>{result.years.map(y=><tr key={y.year}><th>{y.year}</th>{[y.stockValueCents,y.homeValueCents,y.mortgageBalanceCents,y.equityCents,y.saleProceedsCents,y.ownerOutlayCents,y.rentCents,y.stockContributionCents].map((v,i)=><td key={i}>{cash(v)}</td>)}</tr>)}</tbody></table></div></section></>
}
function Chart({result,scrub,setScrub}:{result:Extract<ReturnType<typeof calculateInvestmentComparison>,{ok:true}>["result"];scrub:number;setScrub:(n:number|null)=>void}){const w=1000,h=300,p=28,max=Math.max(...result.months.flatMap(m=>[m.stockValueCents,m.equityCents,m.saleProceedsCents]),1),x=(i:number)=>p+i/(result.months.length-1)*(w-p*2),y=(v:number)=>h-p-Math.max(0,v)/max*(h-p*2),path=(get:(m:typeof result.months[number])=>number)=>result.months.map((m,i)=>`${i?"L":"M"}${x(i)},${y(get(m))}`).join(" ");return <div className="chart-wrap"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Line chart comparing the projected stock portfolio, home equity, and hypothetical net sale proceeds"><path className="grid" d={`M${p},${h-p} H${w-p}`}/><path className="stock-line" d={path(m=>m.stockValueCents)}/><path className="equity-line" d={path(m=>m.equityCents)}/><path className="sale-line" d={path(m=>m.saleProceedsCents)}/><line className="scrubber" x1={x(scrub)} x2={x(scrub)} y1={p} y2={h-p}/>{[...result.equityCrossovers,...result.saleCrossovers].map((c,i)=><circle key={i} className="crossover" cx={x(c.month)} cy={y(result.months[c.month].stockValueCents)} r="4"><title>Crossover in year {c.year}</title></circle>)}</svg><input className="chart-range" aria-label="Explore projection month" type="range" min="0" max={result.months.length-1} value={scrub} onChange={e=>setScrub(Number(e.target.value))}/></div>}
